### ISSUE TITLE
torchaudio have no attribute magphase?

### ISSUE THREAD

**Issue by Noumanijaz744** [markanderson96/DCASE2021#4]
dear sir i am working to reproduce the results of this work but i am getting the bugs of magphase which i also didnt find in the torchaudio documentation ? can you please elaborate that is their any alternative command for this in the new version of torch audio ?

**Comment by markanderson96** [comment]
The magphase function was removed in Torchaudio 0.11 onward. But it was really just a utility function that returned two well known operations to find the phase and magnitude of a complex number.

Can be quite easily replicated by the following formulae (expanding them to take tensors)
https://en.wikipedia.org/wiki/Complex_number#Polar_complex_plane

Torch has recently extended complex number support so this may also be of interest 
https://pytorch.org/docs/stable/complex_numbers.html#angle-and-abs

Also thanks for the interest in the work, if you use it in research please cite us!

```
@techreport{Anderson2021,
    Author = "Anderson, Mark and Harte, Naomi",
    title = "Bioacoustic Event Detection with Prototypical Networks and Data Augmentation",
    institution = "DCASE2021 Challenge",
    year = "2021",
    month = "June",
}
```

**Comment by markanderson96** [comment]
Torch/Torchaudio and Pytorch Lightning have changed significantly since this codes release, so using a virtual environment and installing the packages from requirements.txt is recommended.

**Comment by Noumanijaz744** [comment]
thank you so much for your reply can you please tell me which version of
python have you used for implementing this task because i have tried to use
python 3.8 it giving me the incompatibility issue while installing the
packages from the requirements.txt file?
thank you so much for your time

Best Regards
Nouman Ijaz
Research Scholar ,
South China University of Technology, Guangzhou China.

**Comment by markanderson96** [comment]
I'm not sure which, but it was likely python 3.7

**Comment by Noumanijaz744** [comment]
after having requirements.txt library installation their is still the issue
exist.

Best Regards
Nouman Ijaz
Research Scholar ,
South China University of Technology, Guangzhou China.

**Comment by markanderson96** [comment]
If its an issue running the code, can you post the traceback?
You can implement the magphase function manually using the information [here](https://github.com/markanderson96/DCASE2021/issues/4#issuecomment-1341102708).

If its an issue with libraries, I'm afraid I no longer know which version of python was used as the environment has been deleted. Alternatively you can manually resolve the dependencies (this requires much more work unfortunately)
